server:
    port: ${SERVER.PORT}

spring:
    config:
        import: 'aws-parameterstore:'
        activate:
            on-profile: dev

    datasource:
        url: jdbc:mysql://${MY_SQL.HOST}:${MY_SQL.PORT}/${MY_SQL.DATABASE}?useSSL=false&serverTimezone=Asia/Seoul
        username: ${DB.USERNAME}
        password: ${DB.PASSWORD}

    jpa:
        hibernate:
            ddl-auto: ${JPA.DDL_AUTO}

    redis:
        host: ${REDIS.HOST}
        port: 6379
        password: ${REDIS.PASSWORD}

# JWT
jwt:
    token:
        access:
            expiration: 86_400_000 # 1일

# cors
allowed-origin: ${DOMAIN}
# cors

# domain
domain: ${DOMAIN}
