server:
    port: 8090

spring:
    config:
        import: 'aws-parameterstore:'
        activate:
            on-profile: dev

    datasource:
        url: jdbc:mysql://${MY_SQL.HOST}:${MY_SQL.PORT}/${MY_SQL.DATABASE}?useSSL=false&serverTimezone=Asia/Seoul
        username: ${DB.USERNAME}
        password: ${DB.PASSWORD}

    redis:
        host: ${REDIS.HOST}
        port: 6379
        password: ${REDIS.PASSWORD}